unit UDM_PEDIDOC;

interface

uses
  SysUtils, Classes, frxClass, frxExportPDF, frxRich, frxDBSet, DB, frxCross, 
  dxmdaset, frxDesgn, FireDAC.Stan.Intf, FireDAC.Stan.Option, 
  FireDAC.Stan.Param, FireDAC.Stan.Error, FireDAC.DatS, FireDAC.Phys.Intf, 
  FireDAC.DApt.Intf, FireDAC.Stan.Async, FireDAC.DApt, FireDAC.Comp.DataSet, 
  FireDAC.Comp.Client, frxBarcode;

type
  TDM_PEDIDOC = class(TDataModule)
    FR_PEDIDO_CLIENTE: TfrxReport;
    pedido: TfrxDBDataset;
    embalagem: TfrxDBDataset;
    empresa: TfrxDBDataset;
    unidade: TfrxDBDataset;
    transp: TfrxDBDataset;
    frxRichObject1: TfrxRichObject;
    frxPDFExport1: TfrxPDFExport;
    Qryunid: TFDQuery;
    dsunid: TDataSource;
    QryPedPecas: TFDQuery;
    DSPedPecas: TDataSource;
    Qryemb: TFDQuery;
    dsemb: TDataSource;
    QryTransp: TFDQuery;
    DSTransp: TDataSource;
    QryunidCODID: TIntegerField;
    QryunidUNI_CODIGO: TStringField;
    QryunidFATOR: TFloatField;
    QryunidFATOR_KG: TFloatField;
    QryembDESCRICAO: TStringField;
    QryembPESO: TFloatField;
    QryTranspTRANSP_ID: TFDAutoIncField;
    QryTranspTRANSP_NOME: TStringField;
    QryTranspTEL1: TStringField;
    QryTranspTEL2: TStringField;
    QryRecebimentos: TFDQuery;
    DsRecebimentos: TDataSource;
    QryRecebimentosCONTROLE: TIntegerField;
    QryRecebimentosTIPO: TStringField;
    QryRecebimentosDOCUMENTO: TStringField;
    QryRecebimentosFORMA: TStringField;
    QryRecebimentosVALOR: TFloatField;
    QryRecebimentosBCO: TStringField;
    QryRecebimentosCONTA: TStringField;
    QryRecebimentosCHEQUE: TStringField;
    QryRecebimentosCARTAO_COD: TIntegerField;
    QryRecebimentosCARTAO: TStringField;
    QryRecebimentosNRCARTAO: TStringField;
    QryRecebimentosAUTORIZACAO: TStringField;
    QryRecebimentosPARCELAS: TIntegerField;
    QryRecebimentosCLIENTE: TStringField;
    QryRecebimentosID_CREDITO: TIntegerField;
    Recebimento: TfrxDBDataset;
    dxMemData1: TdxMemData;
    frxCrossObject1: TfrxCrossObject;
    QryTranspTRANSP_FANTASIA: TStringField;
    QryTranspENDTRANS: TStringField;
    FRD_PEDIDOC: TfrxDesigner;
    QryCtaReceber: TFDQuery;
    DsCtaReceber: TDataSource;
    QryCtaReceberCod_Cliente: TIntegerField;
    QryCtaReceberFILIAL: TIntegerField;
    QryCtaReceberIDCTREC: TFDAutoIncField;
    QryCtaReceberRefOrigem: TStringField;
    QryCtaReceberParcela: TIntegerField;
    QryCtaReceberPortador: TStringField;
    QryCtaReceberEspDoc: TStringField;
    QryCtaReceberTipoCobr: TStringField;
    QryCtaReceberCateg: TStringField;
    QryCtaReceberClass: TStringField;
    QryCtaReceberValorDocumento: TFloatField;
    QryCtaReceberSaldoDocumento: TFloatField;
    QryCtaReceberIDREC: TStringField;
    QryCtaReceberNF: TStringField;
    QryCtaReceberNOSSONRO: TStringField;
    QryCtaReceberCTRL: TIntegerField;
    QryCtaReceberNF_ID: TIntegerField;
    QryCtaReceberVALOR_DESCONTO: TFloatField;
    CtaReceber: TfrxDBDataset;
    QryParcelas: TFDQuery;
    QryParcelasPEDID: TIntegerField;
    QryParcelasNUMERO: TStringField;
    QryParcelasPARCELA: TStringField;
    QryParcelasVALOR: TFloatField;
    DsParcelas: TDataSource;
    parcelas: TfrxDBDataset;
    QryCtaReceberDocumento: TStringField;
    QryCtaReceberDtEmissao: TSQLTimeStampField;
    QryCtaReceberDtVencimento: TSQLTimeStampField;
    QryCtaReceberIDORIG: TStringField;
    QryCtaReceberDataPgto: TSQLTimeStampField;
    QryParcelasVENCTO: TSQLTimeStampField;
    QryRecebimentosDATA: TSQLTimeStampField;
    QryRecebimentosVENCIMENTO: TSQLTimeStampField;
    frxBarCodeObject1: TfrxBarCodeObject;
    qryEMPRESAS: TFDQuery;
    qryEMPRESASDIAG_EMPRESA: TIntegerField;
    qryEMPRESASRAZAO_SOCIAL: TStringField;
    qryEMPRESASFANTASIA: TStringField;
    qryEMPRESASABREVIATURA: TStringField;
    qryEMPRESASEMPRESA_CNPJ: TStringField;
    qryEMPRESASEMPRESA_IE: TStringField;
    qryEMPRESASEMPRESA_IEST: TStringField;
    qryEMPRESASEMPRESA_IM: TStringField;
    qryEMPRESASENDERECO: TStringField;
    qryEMPRESASENDERECO_NUM: TStringField;
    qryEMPRESASENDERECO_COMPL: TStringField;
    qryEMPRESASBAIRRO: TStringField;
    qryEMPRESASCIDADE: TStringField;
    qryEMPRESASUF: TStringField;
    qryEMPRESASCEP: TStringField;
    qryEMPRESASTEL1: TStringField;
    qryEMPRESASTEL2: TStringField;
    qryEMPRESASFAX: TStringField;
    qryEMPRESASSITE: TStringField;
    qryEMPRESASEMAIL: TStringField;
    qryEMPRESASCUSTO_CAPITAL: TFloatField;
    qryEMPRESASNRO_UNIDADE: TIntegerField;
    qryEMPRESASTEXTO_LIVRE: TStringField;
    qryEMPRESASSERIE_ID: TIntegerField;
    qryEMPRESASENDERECOENT: TStringField;
    qryEMPRESASBAIRROENT: TStringField;
    qryEMPRESASCEPENT: TStringField;
    qryEMPRESASCIDADEENT: TStringField;
    qryEMPRESASUFENT: TStringField;
    qryEMPRESASCONTADOR: TStringField;
    qryEMPRESASTEL_CONTADOR: TStringField;
    qryEMPRESASFUNDO: TStringField;
    qryEMPRESASLOGO: TStringField;
    qryEMPRESASEXPIRA: TSQLTimeStampField;
    qryEMPRESASFLAG: TStringField;
    qryEMPRESASSIMPLES: TStringField;
    qryEMPRESASPEDIDO: TStringField;
    qryEMPRESASCODCID_IBGE: TIntegerField;
    qryEMPRESASUF_IBGE: TStringField;
    qryEMPRESASNFE_ESQUEMAS: TStringField;
    qryEMPRESASNFE_LOG: TStringField;
    qryEMPRESASNFE_MODELO: TStringField;
    qryEMPRESASNFE_SERIE: TStringField;
    qryEMPRESASNFEINI: TStringField;
    qryEMPRESASNFE: TStringField;
    qryEMPRESASCOD_CLIENTE: TIntegerField;
    qryEMPRESASIMAGENS: TStringField;
    qryEMPRESASSUFRAMA: TStringField;
    qryEMPRESASCRT: TStringField;
    qryEMPRESASCPF_CONTADOR: TStringField;
    qryEMPRESASCRC_CONTADOR: TStringField;
    qryEMPRESASID_BOLETO: TIntegerField;
    qryEMPRESASLOGOTIPO: TStringField;
    qryEMPRESASCOD_CONTADOR: TIntegerField;
    qryEMPRESASNFSEINI: TStringField;
    qryEMPRESASSCHEMASNFSE: TStringField;
    qryEMPRESASEMAIL_AUTO: TStringField;
    qryEMPRESASPROVEDOR: TStringField;
    qryEMPRESASUSUARIO: TStringField;
    qryEMPRESASSENHA: TStringField;
    qryEMPRESASPORTA: TIntegerField;
    qryEMPRESASRAS: TStringField;
    qryEMPRESASSSL: TStringField;
    qryEMPRESASMENSAGEM: TMemoField;
    qryEMPRESASPASTA_ORG_XML: TStringField;
    qryEMPRESASMDFE_LOG: TStringField;
    qryEMPRESASMDFEINI: TStringField;
    qryEMPRESASRNTRC: TStringField;
    qryEMPRESASAPOLICE: TStringField;
    qryEMPRESASAVERBACAO: TStringField;
    qryEMPRESASSEGURADORA: TStringField;
    qryEMPRESASBLOQUEIO: TStringField;
    qryEMPRESASICMS: TFloatField;
    qryEMPRESASEND_COMPLETO: TStringField;
    qryEMPRESASDATA_INICIAL: TSQLTimeStampField;
    dsrEMPRESAS: TDataSource;
    QryPedPecasSERASA: TStringField;
    QryPedPecasAUTOID: TFDAutoIncField;
    QryPedPecasPEDIDO: TIntegerField;
    QryPedPecasMAQ: TStringField;
    QryPedPecasCODID: TIntegerField;
    QryPedPecasCOD_INTERNO: TStringField;
    QryPedPecasDESCRICAOPROD: TStringField;
    QryPedPecasMARCA: TStringField;
    QryPedPecasEMBALAGEM: TStringField;
    QryPedPecasUNIDADE: TStringField;
    QryPedPecasESTOQUE_ID: TIntegerField;
    QryPedPecasQUANT: TFloatField;
    QryPedPecasALIQ_IPI: TFloatField;
    QryPedPecasVLR_IPI: TFloatField;
    QryPedPecasALIQ_ICMS: TFloatField;
    QryPedPecasVLR_ICMS: TFloatField;
    QryPedPecasVLR_CUSTO: TFloatField;
    QryPedPecasVLR_UNIT: TFloatField;
    QryPedPecasVLR_DOLAR: TFloatField;
    QryPedPecasVLR_TOTAL: TFloatField;
    QryPedPecasMOVIMENTOU_ESTOQUE: TStringField;
    QryPedPecasUSRLIB: TIntegerField;
    QryPedPecasQTDEMB: TIntegerField;
    QryPedPecasIDEMB: TIntegerField;
    QryPedPecasCOMISSAO: TFloatField;
    QryPedPecasFAT: TStringField;
    QryPedPecasMOEDA_ID: TIntegerField;
    QryPedPecasPESO: TFloatField;
    QryPedPecasQTDE_FAT: TFloatField;
    QryPedPecasQTDE_LIB: TFloatField;
    QryPedPecasSEUITEM: TIntegerField;
    QryPedPecasENTREGA: TStringField;
    QryPedPecasCOMPLEMENTO: TStringField;
    QryPedPecasORDEM: TIntegerField;
    QryPedPecasCODBARRAS: TStringField;
    QryPedPecasQTDE_TEMP: TFloatField;
    QryPedPecasCOR: TStringField;
    QryPedPecasPORTA_TIPO: TStringField;
    QryPedPecasGRAVACAO: TStringField;
    QryPedPecasLADOS: TStringField;
    QryPedPecasCFOP_ID: TIntegerField;
    QryPedPecasQTDE_ENTREGUE: TFloatField;
    QryPedPecasDESCRICAO: TStringField;
    QryPedPecasNOME: TStringField;
    QryPedPecasTEL1: TStringField;
    QryPedPecasTEL2: TStringField;
    QryPedPecasEMAIL: TStringField;
    QryPedPecasPEDID: TFDAutoIncField;
    QryPedPecasFILIAL: TIntegerField;
    QryPedPecasDATA: TSQLTimeStampField;
    QryPedPecasSEUPEDIDO: TIntegerField;
    QryPedPecasCOD_CLIENTE: TIntegerField;
    QryPedPecasTIPO: TIntegerField;
    QryPedPecasFPGTO_COD: TIntegerField;
    QryPedPecasFPGTO: TStringField;
    QryPedPecasDT_ENTREGA: TSQLTimeStampField;
    QryPedPecasPRAZO_ENTREGA: TStringField;
    QryPedPecasVENDEDOR_ID: TIntegerField;
    QryPedPecasVENDEDOR: TStringField;
    QryPedPecasQUANT_ITENS: TFloatField;
    QryPedPecasFRETE_CONTA: TIntegerField;
    QryPedPecasVLRFRETE: TFloatField;
    QryPedPecasTOTAL_PEDIDO: TFloatField;
    QryPedPecasOBS: TMemoField;
    QryPedPecasCOMPRADOR: TStringField;
    QryPedPecasTRANSPORTADORA: TIntegerField;
    QryPedPecasVOLUMES: TStringField;
    QryPedPecasPOSICAO: TStringField;
    QryPedPecasPROD_IMPRESSO: TStringField;
    QryPedPecasNF: TIntegerField;
    QryPedPecasSTATUS: TStringField;
    QryPedPecasPEDIDOCLI: TStringField;
    QryPedPecasFOBCIF: TIntegerField;
    QryPedPecasDT_FECHAMENTO: TSQLTimeStampField;
    QryPedPecasCOTACAO: TIntegerField;
    QryPedPecasREQCOMPRA: TIntegerField;
    QryPedPecasPA: TIntegerField;
    QryPedPecasASS1: TIntegerField;
    QryPedPecasASS2: TIntegerField;
    QryPedPecasASS3: TIntegerField;
    QryPedPecasASS4: TIntegerField;
    QryPedPecasTIPOCOBR: TStringField;
    QryPedPecasMINUTA: TIntegerField;
    QryPedPecasSEL: TStringField;
    QryPedPecasCOD_TABELA: TIntegerField;
    QryPedPecasORIGEM: TIntegerField;
    QryPedPecasPERC_DESC: TFloatField;
    QryPedPecasVLR_DESC: TFloatField;
    QryPedPecasVIA: TIntegerField;
    QryPedPecasDATA_FATURAMENTO: TSQLTimeStampField;
    QryPedPecasVENDEDOR2: TIntegerField;
    QryPedPecasOPERACAO: TStringField;
    QryPedPecasFILIAL_FATUR: TIntegerField;
    QryPedPecasCOD_CLIENTE_FATUR: TIntegerField;
    QryPedPecasESPECIAL: TStringField;
    QryPedPecasPERC_ESPECIAL: TFloatField;
    QryPedPecasCOD_TABELA_ESPECIAL: TIntegerField;
    QryPedPecasFILIAL_PEDIDO: TIntegerField;
    QryPedPecasCIDADE: TStringField;
    QryPedPecasCEP: TStringField;
    QryPedPecasFANTASIA: TStringField;
    QryPedPecasENDERECO: TStringField;
    QryPedPecasBAIRRO: TStringField;
    QryPedPecasUF: TStringField;
    QryPedPecasUF_ENT: TStringField;
    QryPedPecasUF_COB: TStringField;
    QryPedPecasCIDADE_ENT: TStringField;
    QryPedPecasCIDADE_COB: TStringField;
    QryPedPecasCEP_ENT: TStringField;
    QryPedPecasCEP_COB: TStringField;
    QryPedPecasDesc_TpCobr: TStringField;
    QryPedPecasENDERECO_ENT: TStringField;
    QryPedPecasBAIRRO_ENT: TStringField;
    QryPedPecasENDERECO_COB: TStringField;
    QryPedPecasBAIRRO_COB: TStringField;
    QryPedPecasESTOQUE_DESCR: TStringField;
    QryPedPecasCPF_CNPJ: TStringField;
    QryPedPecasRG_INSC: TStringField;
    QryPedPecasQTDE_VOL: TFloatField;
    QryPedPecasTRANSP_NOME: TStringField;
    QryPedPecasTELTRANS: TStringField;
    QryPedPecasCONTATO1: TStringField;
    QryPedPecasUFTRANS: TStringField;
    QryPedPecasCONTATO3: TStringField;
    QryPedPecasDEPOSITO: TStringField;
    QryPedPecasTRANSP_FANTASIA: TStringField;
    QryPedPecasCLIENTE_DESDE: TSQLTimeStampField;
    QryPedPecasENDTRANS: TStringField;
    QryPedPecasCOLETA: TStringField;
    QryPedPecasQTDE_SALDO: TFloatField;
    QryPedPecasVALOR_SALDO: TFloatField;
    QryPedPecasVLSEMIPI_SALDO: TFloatField;
    QryPedPecasVOLUME: TStringField;
    QryPedPecas2: TFDQuery;
    QryPedPecas2SERASA: TStringField;
    QryPedPecas2AUTOID: TFDAutoIncField;
    QryPedPecas2PEDIDO: TIntegerField;
    QryPedPecas2MAQ: TStringField;
    QryPedPecas2CODID: TIntegerField;
    QryPedPecas2COD_INTERNO: TStringField;
    QryPedPecas2DESCRICAOPROD: TStringField;
    QryPedPecas2MARCA: TStringField;
    QryPedPecas2EMBALAGEM: TStringField;
    QryPedPecas2UNIDADE: TStringField;
    QryPedPecas2ESTOQUE_ID: TIntegerField;
    QryPedPecas2QUANT: TFloatField;
    QryPedPecas2ALIQ_IPI: TFloatField;
    QryPedPecas2VLR_IPI: TFloatField;
    QryPedPecas2ALIQ_ICMS: TFloatField;
    QryPedPecas2VLR_ICMS: TFloatField;
    QryPedPecas2VLR_CUSTO: TFloatField;
    QryPedPecas2VLR_UNIT: TFloatField;
    QryPedPecas2VLR_DOLAR: TFloatField;
    QryPedPecas2VLR_TOTAL: TFloatField;
    QryPedPecas2MOVIMENTOU_ESTOQUE: TStringField;
    QryPedPecas2USRLIB: TIntegerField;
    QryPedPecas2QTDEMB: TIntegerField;
    QryPedPecas2IDEMB: TIntegerField;
    QryPedPecas2COMISSAO: TFloatField;
    QryPedPecas2FAT: TStringField;
    QryPedPecas2MOEDA_ID: TIntegerField;
    QryPedPecas2PESO: TFloatField;
    QryPedPecas2QTDE_FAT: TFloatField;
    QryPedPecas2QTDE_LIB: TFloatField;
    QryPedPecas2SEUITEM: TIntegerField;
    QryPedPecas2ENTREGA: TStringField;
    QryPedPecas2COMPLEMENTO: TStringField;
    QryPedPecas2ORDEM: TIntegerField;
    QryPedPecas2CODBARRAS: TStringField;
    QryPedPecas2QTDE_TEMP: TFloatField;
    QryPedPecas2COR: TStringField;
    QryPedPecas2PORTA_TIPO: TStringField;
    QryPedPecas2GRAVACAO: TStringField;
    QryPedPecas2LADOS: TStringField;
    QryPedPecas2CFOP_ID: TIntegerField;
    QryPedPecas2QTDE_ENTREGUE: TFloatField;
    QryPedPecas2DESCRICAO: TStringField;
    QryPedPecas2NOME: TStringField;
    QryPedPecas2TEL1: TStringField;
    QryPedPecas2TEL2: TStringField;
    QryPedPecas2EMAIL: TStringField;
    QryPedPecas2PEDID: TFDAutoIncField;
    QryPedPecas2FILIAL: TIntegerField;
    QryPedPecas2DATA: TSQLTimeStampField;
    QryPedPecas2SEUPEDIDO: TIntegerField;
    QryPedPecas2COD_CLIENTE: TIntegerField;
    QryPedPecas2TIPO: TIntegerField;
    QryPedPecas2FPGTO_COD: TIntegerField;
    QryPedPecas2FPGTO: TStringField;
    QryPedPecas2DT_ENTREGA: TSQLTimeStampField;
    QryPedPecas2PRAZO_ENTREGA: TStringField;
    QryPedPecas2VENDEDOR_ID: TIntegerField;
    QryPedPecas2VENDEDOR: TStringField;
    QryPedPecas2QUANT_ITENS: TFloatField;
    QryPedPecas2FRETE_CONTA: TIntegerField;
    QryPedPecas2VLRFRETE: TFloatField;
    QryPedPecas2TOTAL_PEDIDO: TFloatField;
    QryPedPecas2OBS: TMemoField;
    QryPedPecas2COMPRADOR: TStringField;
    QryPedPecas2TRANSPORTADORA: TIntegerField;
    QryPedPecas2VOLUMES: TStringField;
    QryPedPecas2POSICAO: TStringField;
    QryPedPecas2PROD_IMPRESSO: TStringField;
    QryPedPecas2NF: TIntegerField;
    QryPedPecas2STATUS: TStringField;
    QryPedPecas2PEDIDOCLI: TStringField;
    QryPedPecas2FOBCIF: TIntegerField;
    QryPedPecas2DT_FECHAMENTO: TSQLTimeStampField;
    QryPedPecas2COTACAO: TIntegerField;
    QryPedPecas2REQCOMPRA: TIntegerField;
    QryPedPecas2PA: TIntegerField;
    QryPedPecas2ASS1: TIntegerField;
    QryPedPecas2ASS2: TIntegerField;
    QryPedPecas2ASS3: TIntegerField;
    QryPedPecas2ASS4: TIntegerField;
    QryPedPecas2TIPOCOBR: TStringField;
    QryPedPecas2MINUTA: TIntegerField;
    QryPedPecas2SEL: TStringField;
    QryPedPecas2COD_TABELA: TIntegerField;
    QryPedPecas2ORIGEM: TIntegerField;
    QryPedPecas2PERC_DESC: TFloatField;
    QryPedPecas2VLR_DESC: TFloatField;
    QryPedPecas2VIA: TIntegerField;
    QryPedPecas2DATA_FATURAMENTO: TSQLTimeStampField;
    QryPedPecas2VENDEDOR2: TIntegerField;
    QryPedPecas2OPERACAO: TStringField;
    QryPedPecas2FILIAL_FATUR: TIntegerField;
    QryPedPecas2COD_CLIENTE_FATUR: TIntegerField;
    QryPedPecas2ESPECIAL: TStringField;
    QryPedPecas2PERC_ESPECIAL: TFloatField;
    QryPedPecas2COD_TABELA_ESPECIAL: TIntegerField;
    QryPedPecas2FILIAL_PEDIDO: TIntegerField;
    QryPedPecas2CIDADE: TStringField;
    QryPedPecas2CEP: TStringField;
    QryPedPecas2FANTASIA: TStringField;
    QryPedPecas2ENDERECO: TStringField;
    QryPedPecas2BAIRRO: TStringField;
    QryPedPecas2UF: TStringField;
    QryPedPecas2UF_ENT: TStringField;
    QryPedPecas2UF_COB: TStringField;
    QryPedPecas2CIDADE_ENT: TStringField;
    QryPedPecas2CIDADE_COB: TStringField;
    QryPedPecas2CEP_ENT: TStringField;
    QryPedPecas2CEP_COB: TStringField;
    QryPedPecas2Desc_TpCobr: TStringField;
    QryPedPecas2ENDERECO_ENT: TStringField;
    QryPedPecas2BAIRRO_ENT: TStringField;
    QryPedPecas2ENDERECO_COB: TStringField;
    QryPedPecas2BAIRRO_COB: TStringField;
    QryPedPecas2ESTOQUE_DESCR: TStringField;
    QryPedPecas2CPF_CNPJ: TStringField;
    QryPedPecas2RG_INSC: TStringField;
    QryPedPecas2QTDE_VOL: TFloatField;
    QryPedPecas2TRANSP_NOME: TStringField;
    QryPedPecas2TELTRANS: TStringField;
    QryPedPecas2CONTATO1: TStringField;
    QryPedPecas2UFTRANS: TStringField;
    QryPedPecas2CONTATO3: TStringField;
    QryPedPecas2DEPOSITO: TStringField;
    QryPedPecas2TRANSP_FANTASIA: TStringField;
    QryPedPecas2CLIENTE_DESDE: TSQLTimeStampField;
    QryPedPecas2ENDTRANS: TStringField;
    QryOrdemCompra: TFDQuery;
    QryOrdemCompraCOD_CLIENTE: TIntegerField;
    QryOrdemCompraPEDIDO: TIntegerField;
    QryOrdemCompraDATA: TSQLTimeStampField;
    QryOrdemCompraFILIAL_PEDIDO: TIntegerField;
    QryOrdemCompraPEDID: TFDAutoIncField;
    QryOrdemCompraPEDIDOCLI: TStringField;
    QryItensPed: TFDQuery;
    QryItensPedAUTOID: TFDAutoIncField;
    QryItensPedPEDID: TIntegerField;
    QryItensPedPEDIDO: TIntegerField;
    QryItensPedCODID: TIntegerField;
    QryItensPedCOD_INTERNO: TStringField;
    QryItensPedDESCRICAOPROD: TStringField;
    QryItensPedSEUPEDIDO: TStringField;
    QryItensPedSEUITEM: TIntegerField;
    QryItensPedORDEM: TIntegerField;
    QryAtualizaItens: TFDQuery;
    FDAutoIncField1: TFDAutoIncField;
    IntegerField1: TIntegerField;
    IntegerField2: TIntegerField;
    IntegerField3: TIntegerField;
    StringField1: TStringField;
    StringField2: TStringField;
    StringField3: TStringField;
    IntegerField4: TIntegerField;
    IntegerField5: TIntegerField;
    QryPedPecasVLR_ICMSSUB: TFloatField;
    QryPedPecasST: TStringField;
    QryPedPecasIVA: TFloatField;
    QryPedPecasTOT_ICMSST: TFloatField;
    QryPedPecasTOT_ICMS: TFloatField;
    QryPedPecasTOT_IPI: TFloatField;
    QryPedPecasVLR_BASE_ICMSST: TFloatField;
    QryPedPecasVLR_BASE_ICMS: TFloatField;
    QryPedPecasTOT_BASE_ICMSST: TFloatField;
    QryPedPecasTOT_BASE_ICMS: TFloatField;
    procedure QryPedPecasCalcFields(DataSet: TDataSet);
    procedure qryEMPRESASCalcFields(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DM_PEDIDOC: TDM_PEDIDOC;

implementation

uses
  untFuncoes_Advensys, UDmdPrincipal;

{$R *.dfm}

procedure TDM_PEDIDOC.qryEMPRESASCalcFields(DataSet: TDataSet);
begin
  qryEMPRESASEND_COMPLETO.Value := qryEMPRESASENDERECO.Value +', '+qryEMPRESASENDERECO_NUM.Value+' - '+
                                   qryEMPRESASENDERECO_COMPL.Value;// +', '+qryEMPRESASENDERECO_NUM.Value+' - '+

end;

procedure TDM_PEDIDOC.QryPedPecasCalcFields(DataSet: TDataSet);
var
  resto : real;
begin
  QryPedPecasCOLETA.Value := Iif(QryPedPecasFRETE_CONTA.Value = 1 , 'POSTO NO CLIENTE/TRANSPORTADORA','SOLICITAR COLETA') ;

  QryPedPecasQTDE_SALDO.Value     := QryPedPecasQUANT.Value - QryPedPecasQTDE_FAT.Value;
  QryPedPecasVALOR_SALDO.Value    := (QryPedPecasQTDE_SALDO.Value * QryPedPecasVLR_UNIT.Value)+
                                     (QryPedPecasQTDE_SALDO.Value * QryPedPecasVLR_UNIT.Value)*(QryPedPecasALIQ_IPI.Value/100);
  QryPedPecasVLSEMIPI_SALDO.Value := (QryPedPecasQTDE_SALDO.Value * QryPedPecasVLR_UNIT.Value);
  if QryPedPecasQTDE_VOL.Value > 0 then
  begin
    QryPedPecasVOLUME.Value := FormatFloat('#',int(QryPedPecasQTDE_LIB.Value/QryPedPecasQTDE_VOL.Value));
    resto  := QryPedPecasQTDE_LIB.Value-(int(QryPedPecasQTDE_LIB.Value/QryPedPecasQTDE_VOL.Value)*QryPedPecasQTDE_VOL.Value);
    if resto > 0 then
       QryPedPecasVOLUME.Value := QryPedPecasVOLUME.Value + ' vol. e ' + FormatFloat('#',resto)+Iif(resto = 1 ,' pc',' pcs');
  end
  else
  begin
    QryPedPecasVOLUME.Value := FormatFloat('#',QryPedPecasQTDE_LIB.Value);
  end;
  (*
  QryPedPecasCOLETA.Value := Iif(QryPedPecasFRETE_CONTA.Value = 1 , 'POSTO NO CLIENTE/TRANSPORTADORA','SOLICITAR COLETA') ;

  QryPedPecasQTDE_SALDO.Value     := QryPedPecasQUANT.Value - QryPedPecasQTDE_FAT.Value;
  QryPedPecasVALOR_SALDO.Value    := (QryPedPecasQTDE_SALDO.Value * QryPedPecasVLR_UNIT.Value)+
                                     (QryPedPecasQTDE_SALDO.Value * QryPedPecasVLR_UNIT.Value)*(QryPedPecasALIQ_IPI.Value/100);
  QryPedPecasVLSEMIPI_SALDO.Value := (QryPedPecasQTDE_SALDO.Value * QryPedPecasVLR_UNIT.Value);
  if QryPedPecasQTDE_VOL.Value > 0 then
  begin
    QryPedPecasVOLUME.Value := FormatFloat('#',int(QryPedPecasQTDE_LIB.Value/QryPedPecasQTDE_VOL.Value));
    resto  := QryPedPecasQTDE_LIB.Value-(int(QryPedPecasQTDE_LIB.Value/QryPedPecasQTDE_VOL.Value)*QryPedPecasQTDE_VOL.Value);
    if resto > 0 then
       QryPedPecasVOLUME.Value := QryPedPecasVOLUME.Value + ' vol. e ' + FormatFloat('#',resto)+Iif(resto = 1 ,' pc',' pcs');
  end
  else
  begin
    QryPedPecasVOLUME.Value := FormatFloat('#',QryPedPecasQTDE_LIB.Value);
  end; *)
end;

end.
